import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

const navigationConfig = [
{
        key: 'home',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'nav.Dashboard',
        icon: 'home', // Maps to FcHome
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    
    // {
    //     key: 'Customer',
    //     path: '/Customer',
    //     title: 'Customer',
    //     translateKey: 'nav.Customer',
    //     icon: 'singleMenu',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    // {
    //     key: 'Material',
    //     path: '/Material',
    //     title: 'Material',
    //     translateKey: 'nav.Material',
    //     icon: 'Material',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    // {
    //     key: 'SalesMan',
    //     path: '/SalesMan',
    //     title: 'SalesMan',
    //     translateKey: 'nav.SalesMan',
    //     icon: 'SalesMan',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    // {
    //     key: 'Banks',
    //     path: '/Banks',
    //     title: 'Banks',
    //     translateKey: 'nav.Banks',
    //     icon: 'Banks',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    // {
    //     key: 'SafeDeposits',
    //     path: '/SafeDeposits',
    //     title: 'SafeDeposits',
    //     translateKey: 'nav.SafeDeposits',
    //     icon: 'SafeDeposits',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    // {
    //     key: 'Demand',
    //     path: '/Demand',
    //     title: 'Demand',
    //     translateKey: 'nav.Demand',
    //     icon: 'Demand',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    // {
    //     key: 'Sales',
    //     path: '',
    //     title: 'Sales',
    //     translateKey: 'nav.Sales',
    //     icon: 'Sales',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'collapseSales.SalesOrder',
    //             path: '/SalesOrder',
    //             title: 'SalesOrder',
    //             translateKey: 'nav.collapseSales.SalesOrder',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'collapseSales.MaterialsTransaction',
    //             path: '/MaterialsTransaction',
    //             title: 'MaterialsTransaction',
    //             translateKey: 'nav.collapseSales.MaterialsTransaction',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // },
    // {
    //     key: 'Purchases',
    //     path: '',
    //     title: 'Purchases',
    //     translateKey: 'nav.Purchases',
    //     icon: 'Purchases',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'collapsePurchases.PurchaseOrder',
    //             path: '/PurchaseOrder',
    //             title: 'PurchaseOrder',
    //             translateKey: 'nav.collapsePurchases.PurchaseOrder',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'collapsePurchases.MaterialsTransaction',
    //             path: '/MaterialsTransaction',
    //             title: 'MaterialsTransaction',
    //             translateKey: 'nav.collapsePurchases.MaterialsTransaction',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // },
    // {
    //     key: 'ReportMenu',
    //     path: '',
    //     title: 'ReportMenu',
    //     translateKey: 'nav.ReportMenu.ReportMenu',
    //     icon: 'ReportMenu',
    //     type: NAV_ITEM_TYPE_TITLE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'ReportMenu.collapse',
    //             path: '',
    //             title: 'Group collapse menu',
    //             translateKey: 'nav.ReportMenu.collapse.ReportDesigner',
    //             icon: 'Report',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [],
    //             subMenu: [
    //                 {
    //                     key: 'ReportMenu.collapse.Report',
    //                     path: '/Report',
    //                     title: 'Report',
    //                     translateKey: 'nav.ReportMenu.collapse.Report',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'ReportMenu.collapse.ReportType',
    //                     path: '/ReportType',
    //                     title: 'ReportType',
    //                     translateKey: 'nav.ReportMenu.collapse.ReportType',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'ReportMenu.collapse.Targets',
    //                     path: '/Targets',
    //                     title: 'Targets',
    //                     translateKey: 'nav.ReportMenu.collapse.Targets',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //             ],
    //         },
    //     ],
    // },
    // New routes added per request (English)
    {
        key: 'appointmentBooking',
        path: '/appointment-booking',
        title: 'Appointment Booking',
        translateKey: 'nav.AppointmentBooking',
        icon: 'appointment',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'reservations',
        path: '/reservations',
        title: 'Reservations',
        translateKey: 'nav.Reservations',
        icon: 'reservations',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'vehicleEntry',
        path: '/vehicle-entry',
        title: 'Vehicle Entry',
        translateKey: 'nav.VehicleEntry',
        icon: 'vehicle',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'accounting',
        path: '/accounting',
        title: 'Accounting Screen',
        translateKey: 'nav.Accounting',
        icon: 'accounting',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'clientInfo',
        path: '/client-info',
        title: 'Client Information',
        translateKey: 'nav.ClientInformation',
        icon: 'client',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'branchInspections',
        path: '/branch-inspections',
        title: 'Branch Inspections',
        translateKey: 'nav.BranchInspections',
        icon: 'branchInspections',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'deferredInspections',
        path: '/deferred-inspections',
        title: 'Deferred Inspections',
        translateKey: 'nav.DeferredInspections',
        icon: 'deferred',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'inspectorRecheckRequests',
        path: '/inspector-recheck-requests',
        title: 'Inspector Recheck Requests',
        translateKey: 'nav.InspectorRecheckRequests',
        icon: 'recheck',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'inspectionRequestsFromInspector',
        path: '/inspection-requests-from-inspector',
        title: 'Inspection Requests From Inspector',
        translateKey: 'nav.InspectionRequestsFromInspector',
        icon: 'inspectionRequests',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'carEstimation',
        path: '/car-estimation',
        title: 'Car Estimation',
        translateKey: 'nav.CarEstimation',
        icon: 'estimation',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'previousEstimations',
        path: '/previous-estimations',
        title: 'Previous Estimations',
        translateKey: 'nav.PreviousEstimations',
        icon: 'previousEstimations',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'startInspection',
        path: '/start-inspection',
        title: 'Start Vehicle Inspection',
        translateKey: 'nav.StartInspection',
        icon: 'startInspection',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'completeInspections',
        path: '/complete-inspections',
        title: 'Complete Inspections',
        translateKey: 'nav.CompleteInspections',
        icon: 'complete',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'previousInspections',
        path: '/previous-inspections',
        title: 'Previous Inspections',
        translateKey: 'nav.PreviousInspections',
        icon: 'previousInspections',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'carsirInspections',
        path: '/carsir-inspections',
        title: 'Carsir Inspections',
        translateKey: 'nav.CarsirInspections',
        icon: 'carsir',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'reports',
        path: '',
        title: 'Reports',
        translateKey: 'nav.Reports',
        icon: 'reports',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            { key: 'reports.staffSummary', path: '/reports/staff-summary', title: 'Staff Summary', translateKey: 'nav.reports.staffSummary', icon: 'staffSummary', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
            { key: 'reports.staffDetailed', path: '/reports/staff-detailed', title: 'Staff Detailed', translateKey: 'nav.reports.staffDetailed', icon: 'staffDetailed', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
            { key: 'reports.inspectionsByCheckpoints', path: '/reports/inspections-by-checkpoints', title: 'Inspections by Checkpoints', translateKey: 'nav.reports.inspectionsByCheckpoints', icon: 'checkpoints', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
            { key: 'reports.inspectionsByPaymentMethod', path: '/reports/inspections-by-payment-method', title: 'Inspections by Payment Method', translateKey: 'nav.reports.inspectionsByPaymentMethod', icon: 'paymentMethod', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
            { key: 'reports.byPaymentMethod', path: '/reports/by-payment-method', title: 'By Payment Method', translateKey: 'nav.reports.byPaymentMethod', icon: 'paymentMethod', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
            { key: 'reports.lenders', path: '/reports/lenders', title: 'Lenders', translateKey: 'nav.reports.lenders', icon: 'lenders', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
            { key: 'reports.lendersInspections', path: '/reports/lenders-inspections', title: 'Lenders Inspections', translateKey: 'nav.reports.lendersInspections', icon: 'lenders', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
            { key: 'reports.inspectionsReturned', path: '/reports/inspections-returned', title: 'Inspections Returned from Sending/Auditing/Explanation', translateKey: 'nav.reports.inspectionsReturned', icon: 'recheck', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
            { key: 'reports.estimation', path: '/reports/estimation', title: 'Estimation', translateKey: 'nav.reports.estimation', icon: 'estimation', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
            { key: 'reports.carsirInspectionsDetail', path: '/reports/carsir-inspections-detail', title: 'Carsir Inspections Detail', translateKey: 'nav.reports.carsirInspectionsDetail', icon: 'carsir', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
            { key: 'reports.numberOfCarsirInspections', path: '/reports/number-of-carsir-inspections', title: 'Number of Carsir Inspections', translateKey: 'nav.reports.numberOfCarsirInspections', icon: 'carsir', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
            { key: 'reports.customers', path: '/reports/customers', title: 'Customers', translateKey: 'nav.reports.customers', icon: 'customers', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
            { key: 'reports.auditResponsible', path: '/reports/audit-responsible', title: 'Audit/Explanation Responsible', translateKey: 'nav.reports.auditResponsible', icon: 'auditResponsible', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
        ],
    },
    {
        key: 'settings',
        path: '',
        title: 'Settings',
        translateKey: 'nav.Settings',
        icon: 'settings',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'settings.usersAndPermissions',
                path: '',
                title: 'Users and Permissions',
                translateKey: 'nav.settings.usersAndPermissions',
                icon: 'users',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    { key: 'settings.userGroups', path: '/settings/user-groups', title: 'User Groups', translateKey: 'nav.settings.userGroups', icon: 'userGroups', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'settings.permissionsList', path: '/settings/permissions', title: 'Permissions List', translateKey: 'nav.settings.permissionsList', icon: 'permissions', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'settings.users', path: '/settings/users', title: 'Users', translateKey: 'nav.settings.users', icon: 'users', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'settings.usersAllBranches', path: '/settings/users-all-branches', title: 'Users (All Branches)', translateKey: 'nav.settings.usersAllBranches', icon: 'users', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                ],
            },
            {
                key: 'settings.systemLists',
                path: '',
                title: 'System Lists',
                translateKey: 'nav.settings.systemLists',
                icon: 'systemCheckpoints',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    { key: 'system.vehicleTypes', path: '/settings/system/vehicle-types', title: 'Vehicle Types', translateKey: 'nav.system.vehicleTypes', icon: 'vehicleTypes', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'system.vehicleBodies', path: '/settings/system/vehicle-bodies', title: 'Vehicle Bodies', translateKey: 'nav.system.vehicleBodies', icon: 'vehicleBodies', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'system.vehicleColors', path: '/settings/system/vehicle-colors', title: 'Vehicle Colors', translateKey: 'nav.system.vehicleColors', icon: 'vehicleColors', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'system.countries', path: '/settings/system/countries', title: 'Countries of Origin', translateKey: 'nav.system.countries', icon: 'countries', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'system.fuelTypes', path: '/settings/system/fuel-types', title: 'Fuel Types', translateKey: 'nav.system.fuelTypes', icon: 'fuelTypes', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'system.paymentMethods', path: '/settings/system/payment-methods', title: 'Payment Methods', translateKey: 'nav.system.paymentMethods', icon: 'paymentMethods', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'system.financialInstitutions', path: '/settings/system/financial-institutions', title: 'Financial Institutions', translateKey: 'nav.system.financialInstitutions', icon: 'financialInstitutions', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'system.checkpoints', path: '/settings/system/checkpoints', title: 'Checkpoints', translateKey: 'nav.system.checkpoints', icon: 'systemCheckpoints', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'system.inspectionPackages', path: '/settings/system/inspection-packages', title: 'Inspection Packages', translateKey: 'nav.system.inspectionPackages', icon: 'inspectionPackages', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'system.resetCheckpoints', path: '/settings/system/reset-checkpoints', title: 'Reset Checkpoints', translateKey: 'nav.system.resetCheckpoints', icon: 'resetCheckpoints', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'system.exhibitions', path: '/settings/system/exhibitions', title: 'Exhibitions', translateKey: 'nav.system.exhibitions', icon: 'exhibitions', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'system.cities', path: '/settings/system/cities', title: 'Cities', translateKey: 'nav.system.cities', icon: 'cities', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'system.yildan', path: '/settings/system/yildan', title: 'Yildan', translateKey: 'nav.system.yildan', icon: 'yildan', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'system.branches', path: '/settings/system/branches', title: 'Branches', translateKey: 'nav.system.branches', icon: 'branches', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'system.departments', path: '/settings/system/departments', title: 'Departments', translateKey: 'nav.system.departments', icon: 'departments', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                ],
            },
            {
                key: 'settings.banks',
                path: '',
                title: 'Banks',
                translateKey: 'nav.settings.banks',
                icon: 'lenders',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    { key: 'banks.requests', path: '/settings/banks/requests', title: 'Bank Requests', translateKey: 'nav.banks.requests', icon: 'bankRequests', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'banks.users', path: '/settings/banks/users', title: 'Bank Users', translateKey: 'nav.banks.users', icon: 'bankUsers', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'banks.estimation', path: '/settings/banks/estimation', title: 'Bank Estimation', translateKey: 'nav.banks.estimation', icon: 'bankEstimation', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                    { key: 'banks.ads', path: '/settings/banks/ads', title: 'Bank Ads', translateKey: 'nav.banks.ads', icon: 'bankAds', type: NAV_ITEM_TYPE_ITEM, authority: [], subMenu: [] },
                ],
            },
        ],
    },
]

export default navigationConfig
